# -*- coding: utf-8 -*-
"""Copy of Day4_Pandas_HandsOn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mtE8jvxxMWyhgKmeB5a04CDU7e-HORWO

## 🐼 Day 4: Pandas Hands-On (Student Version)
Write your code in the cells below each instruction.

### Slide 2–3: Series Object
💡 **Task:** Write code to demonstrate this concept based on what was shown in the slide.
"""

# Your code here
import pandas as pd
names=['Viswa', 'Praveen', 'Ibrahim', 'Idrees']
namesSeries=pd.Series(names)
namesSeriestwo=pd.Series(names,index=['B','J','S','M'])
print(namesSeriestwo['B'])
print(namesSeriestwo['J'])
print(namesSeriestwo['S'])
print(namesSeriestwo['M'])

#Ex-2
import pandas as pd
Country={'India':'Delhi', 'Pakistan':'Islamabad', 'Srilanka':'Columbo', 'Bangladesh':'Dhaka'}
CountrySeries=pd.Series(Country)
print(CountrySeries)
print(Country['India'])
print(Country['Pakistan'])
print(Country['Srilanka'])
print(Country['Bangladesh'])
print(CountrySeries['India'])
print(CountrySeries['Pakistan'])
print(CountrySeries['Bangladesh'])
print(CountrySeries['Srilanka'])

import pandas as pd
marks1=pd.Series([67,58,89])
marks2=pd.Series([87,98,69])
final_marks=pd.concat([marks1,marks2],ignore_index=True)
print(final_marks)

import pandas as pd
dict1=pd.Series({'MI':5,'CSK':5})
dict2=pd.Series({'RCB':0,'KKR':2})
final_dict=pd.concat([dict1,dict2],ignore_index=True)
print(final_dict)

"""### Slide 5–6: DataFrame from Dictionary
💡 **Task:** Write code to demonstrate this concept based on what was shown in the slide.
"""

# Your code here
import pandas as pd

apple = pd.Series({'Mon': 67, 'Tue': 58, 'Wed': 89})
orange = pd.Series({'Mon': 87, 'Tue': 98, 'Wed': 69})
df = pd.DataFrame({'Apple': apple,'Orange': orange})
print(df)

import pandas as pd

apple = pd.Series([67, 58, 89])
orange = pd.Series([87, 98, 69])
df = pd.DataFrame({'Apple': apple,'Orange': orange})
print(df)

"""### Slide 7: DataFrame from List of Lists
💡 **Task:** Write code to demonstrate this concept based on what was shown in the slide.
"""

# Your code here
import pandas as pd

apple = pd.Series([67, 58, 89])
orange = pd.Series([87, 98, 69])
df = pd.DataFrame({'Apple': apple,'Orange': orange})
print(df)

"""### Slide 9: DataFrame from Series
💡 **Task:** Write code to demonstrate this concept based on what was shown in the slide.
"""

# Your code here

"""### Slide 10: Reading a CSV
💡 **Task:** Write code to demonstrate this concept based on what was shown in the slide.
"""

# Your code here
import pandas as pd
df=pd.read_csv('Iris.csv')
print(df.head())
df.drop('Id',axis=1,inplace=True)
df.head()

df.isnull().sum()

df.info()

df.tail()

df.describe()

df.duplicated().sum()

df.drop_duplicates(inplace=True)
df.duplicated().sum()

import pandas as pd
df=pd.read_csv('Data.csv')
df

df=df.dropna()
df.reset_index(drop=True,inplace=True)
df['city']=['a','b','c','d','s','f','g','e']
df

df.loc[2,'Country']
df.iloc[1:,3]

df.drop('Age',axis=1,inplace=True)
df

"""### Slide 11: Index, Columns, Values
💡 **Task:** Write code to demonstrate this concept based on what was shown in the slide.
"""

# Your code here

"""### Slide 12: Add/Drop Columns
💡 **Task:** Write code to demonstrate this concept based on what was shown in the slide.
"""

# Your code here

"""### Slide 13: Copy vs View
💡 **Task:** Write code to demonstrate this concept based on what was shown in the slide.
"""

# Your code here

"""### Slide 14: iloc vs loc
💡 **Task:** Write code to demonstrate this concept based on what was shown in the slide.
"""

# Your code here

"""### Slide 16: Drop Rows/Columns
💡 **Task:** Write code to demonstrate this concept based on what was shown in the slide.
"""

# Your code here

"""### Slide 18–19: Handling NaNs
💡 **Task:** Write code to demonstrate this concept based on what was shown in the slide.
"""

# Your code here

"""### Slide 22: Boolean Indexing
💡 **Task:** Write code to demonstrate this concept based on what was shown in the slide.
"""

# Your code here

"""### Slide 25: groupby()
💡 **Task:** Write code to demonstrate this concept based on what was shown in the slide.
"""

# Your code here