# -*- coding: utf-8 -*-
"""Copy of practice data_preprocessing_tools.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w7Dji9SOx-8bhTyye-u7pLeYapJolqsp

# Data Preprocessing Tools

## Importing the libraries

## Importing the dataset
"""

import pandas as pd
import numpy as np
import matplotlib

df = pd.read_csv('Data.csv')
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

"""## Taking care of missing data"""

from sklearn.impute import  SimpleImputer

imputer = SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(x[:,1:3])
x[:,1:3]=imputer.transform(x[:,1:3])

x

y

"""## Encoding categorical data"""



"""### Encoding the Independent Variable"""

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
x=np.array(ct.fit_transform(x))

"""### Encoding the Dependent Variable"""

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

"""## Splitting the dataset into the Training set and Test set"""

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

"""## Feature Scaling"""

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

print(x_train)